select * from sakila.dbo.actor
select * from sakila.dbo.country
select * from sakila.dbo.city
select * from sakila.dbo.address
select * from sakila.dbo.language
select * from sakila.dbo.category
select * from sakila.dbo.customer
select * from sakila.dbo.film
select * from sakila.dbo.film_actor
select * from sakila.dbo.film_category
select * from sakila.dbo.film_text
select * from sakila.dbo.inventory
select * from sakila.dbo.staff
select * from sakila.dbo.store
select * from sakila.dbo.payment
select * from sakila.dbo.rental